// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sha512Accel_sha512Accel_Pipeline_VITIS_LOOP_38_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buffer_31_address0,
        buffer_31_ce0,
        buffer_31_we0,
        buffer_31_d0,
        buffer_30_address0,
        buffer_30_ce0,
        buffer_30_we0,
        buffer_30_d0,
        buffer_29_address0,
        buffer_29_ce0,
        buffer_29_we0,
        buffer_29_d0,
        buffer_28_address0,
        buffer_28_ce0,
        buffer_28_we0,
        buffer_28_d0,
        buffer_27_address0,
        buffer_27_ce0,
        buffer_27_we0,
        buffer_27_d0,
        buffer_26_address0,
        buffer_26_ce0,
        buffer_26_we0,
        buffer_26_d0,
        buffer_25_address0,
        buffer_25_ce0,
        buffer_25_we0,
        buffer_25_d0,
        buffer_24_address0,
        buffer_24_ce0,
        buffer_24_we0,
        buffer_24_d0,
        buffer_23_address0,
        buffer_23_ce0,
        buffer_23_we0,
        buffer_23_d0,
        buffer_22_address0,
        buffer_22_ce0,
        buffer_22_we0,
        buffer_22_d0,
        buffer_21_address0,
        buffer_21_ce0,
        buffer_21_we0,
        buffer_21_d0,
        buffer_20_address0,
        buffer_20_ce0,
        buffer_20_we0,
        buffer_20_d0,
        buffer_19_address0,
        buffer_19_ce0,
        buffer_19_we0,
        buffer_19_d0,
        buffer_18_address0,
        buffer_18_ce0,
        buffer_18_we0,
        buffer_18_d0,
        buffer_17_address0,
        buffer_17_ce0,
        buffer_17_we0,
        buffer_17_d0,
        buffer_16_address0,
        buffer_16_ce0,
        buffer_16_we0,
        buffer_16_d0,
        buffer_15_address0,
        buffer_15_ce0,
        buffer_15_we0,
        buffer_15_d0,
        buffer_14_address0,
        buffer_14_ce0,
        buffer_14_we0,
        buffer_14_d0,
        buffer_13_address0,
        buffer_13_ce0,
        buffer_13_we0,
        buffer_13_d0,
        buffer_12_address0,
        buffer_12_ce0,
        buffer_12_we0,
        buffer_12_d0,
        buffer_11_address0,
        buffer_11_ce0,
        buffer_11_we0,
        buffer_11_d0,
        buffer_10_address0,
        buffer_10_ce0,
        buffer_10_we0,
        buffer_10_d0,
        buffer_9_address0,
        buffer_9_ce0,
        buffer_9_we0,
        buffer_9_d0,
        buffer_8_address0,
        buffer_8_ce0,
        buffer_8_we0,
        buffer_8_d0,
        buffer_7_address0,
        buffer_7_ce0,
        buffer_7_we0,
        buffer_7_d0,
        buffer_6_address0,
        buffer_6_ce0,
        buffer_6_we0,
        buffer_6_d0,
        buffer_5_address0,
        buffer_5_ce0,
        buffer_5_we0,
        buffer_5_d0,
        buffer_4_address0,
        buffer_4_ce0,
        buffer_4_we0,
        buffer_4_d0,
        buffer_3_address0,
        buffer_3_ce0,
        buffer_3_we0,
        buffer_3_d0,
        buffer_2_address0,
        buffer_2_ce0,
        buffer_2_we0,
        buffer_2_d0,
        buffer_1_address0,
        buffer_1_ce0,
        buffer_1_we0,
        buffer_1_d0,
        buffer_r_address0,
        buffer_r_ce0,
        buffer_r_we0,
        buffer_r_d0,
        size
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] buffer_31_address0;
output   buffer_31_ce0;
output   buffer_31_we0;
output  [0:0] buffer_31_d0;
output  [4:0] buffer_30_address0;
output   buffer_30_ce0;
output   buffer_30_we0;
output  [0:0] buffer_30_d0;
output  [4:0] buffer_29_address0;
output   buffer_29_ce0;
output   buffer_29_we0;
output  [0:0] buffer_29_d0;
output  [4:0] buffer_28_address0;
output   buffer_28_ce0;
output   buffer_28_we0;
output  [0:0] buffer_28_d0;
output  [4:0] buffer_27_address0;
output   buffer_27_ce0;
output   buffer_27_we0;
output  [0:0] buffer_27_d0;
output  [4:0] buffer_26_address0;
output   buffer_26_ce0;
output   buffer_26_we0;
output  [0:0] buffer_26_d0;
output  [4:0] buffer_25_address0;
output   buffer_25_ce0;
output   buffer_25_we0;
output  [0:0] buffer_25_d0;
output  [4:0] buffer_24_address0;
output   buffer_24_ce0;
output   buffer_24_we0;
output  [0:0] buffer_24_d0;
output  [4:0] buffer_23_address0;
output   buffer_23_ce0;
output   buffer_23_we0;
output  [0:0] buffer_23_d0;
output  [4:0] buffer_22_address0;
output   buffer_22_ce0;
output   buffer_22_we0;
output  [0:0] buffer_22_d0;
output  [4:0] buffer_21_address0;
output   buffer_21_ce0;
output   buffer_21_we0;
output  [0:0] buffer_21_d0;
output  [4:0] buffer_20_address0;
output   buffer_20_ce0;
output   buffer_20_we0;
output  [0:0] buffer_20_d0;
output  [4:0] buffer_19_address0;
output   buffer_19_ce0;
output   buffer_19_we0;
output  [0:0] buffer_19_d0;
output  [4:0] buffer_18_address0;
output   buffer_18_ce0;
output   buffer_18_we0;
output  [0:0] buffer_18_d0;
output  [4:0] buffer_17_address0;
output   buffer_17_ce0;
output   buffer_17_we0;
output  [0:0] buffer_17_d0;
output  [4:0] buffer_16_address0;
output   buffer_16_ce0;
output   buffer_16_we0;
output  [0:0] buffer_16_d0;
output  [4:0] buffer_15_address0;
output   buffer_15_ce0;
output   buffer_15_we0;
output  [0:0] buffer_15_d0;
output  [4:0] buffer_14_address0;
output   buffer_14_ce0;
output   buffer_14_we0;
output  [0:0] buffer_14_d0;
output  [4:0] buffer_13_address0;
output   buffer_13_ce0;
output   buffer_13_we0;
output  [0:0] buffer_13_d0;
output  [4:0] buffer_12_address0;
output   buffer_12_ce0;
output   buffer_12_we0;
output  [0:0] buffer_12_d0;
output  [4:0] buffer_11_address0;
output   buffer_11_ce0;
output   buffer_11_we0;
output  [0:0] buffer_11_d0;
output  [4:0] buffer_10_address0;
output   buffer_10_ce0;
output   buffer_10_we0;
output  [0:0] buffer_10_d0;
output  [4:0] buffer_9_address0;
output   buffer_9_ce0;
output   buffer_9_we0;
output  [0:0] buffer_9_d0;
output  [4:0] buffer_8_address0;
output   buffer_8_ce0;
output   buffer_8_we0;
output  [0:0] buffer_8_d0;
output  [4:0] buffer_7_address0;
output   buffer_7_ce0;
output   buffer_7_we0;
output  [0:0] buffer_7_d0;
output  [4:0] buffer_6_address0;
output   buffer_6_ce0;
output   buffer_6_we0;
output  [0:0] buffer_6_d0;
output  [4:0] buffer_5_address0;
output   buffer_5_ce0;
output   buffer_5_we0;
output  [0:0] buffer_5_d0;
output  [4:0] buffer_4_address0;
output   buffer_4_ce0;
output   buffer_4_we0;
output  [0:0] buffer_4_d0;
output  [4:0] buffer_3_address0;
output   buffer_3_ce0;
output   buffer_3_we0;
output  [0:0] buffer_3_d0;
output  [4:0] buffer_2_address0;
output   buffer_2_ce0;
output   buffer_2_we0;
output  [0:0] buffer_2_d0;
output  [4:0] buffer_1_address0;
output   buffer_1_ce0;
output   buffer_1_we0;
output  [0:0] buffer_1_d0;
output  [4:0] buffer_r_address0;
output   buffer_r_ce0;
output   buffer_r_we0;
output  [0:0] buffer_r_d0;
input  [127:0] size;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln38_fu_611_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln37_fu_642_p1;
reg   [7:0] sizeIndex_fu_168;
wire   [7:0] sizeIndex_1_fu_793_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_sizeIndex_load_1;
reg   [7:0] ap_sig_allocacmp_sizeIndex_load;
reg   [10:0] j_1_fu_172;
wire   [10:0] add_ln38_fu_787_p2;
reg   [10:0] ap_sig_allocacmp_j;
reg    buffer_30_we0_local;
wire   [4:0] trunc_ln38_1_fu_624_p1;
wire   [0:0] tmp_fu_678_p3;
reg    buffer_30_ce0_local;
reg    buffer_29_we0_local;
reg    buffer_29_ce0_local;
reg    buffer_28_we0_local;
reg    buffer_28_ce0_local;
reg    buffer_27_we0_local;
reg    buffer_27_ce0_local;
reg    buffer_26_we0_local;
reg    buffer_26_ce0_local;
reg    buffer_25_we0_local;
reg    buffer_25_ce0_local;
reg    buffer_24_we0_local;
reg    buffer_24_ce0_local;
reg    buffer_23_we0_local;
reg    buffer_23_ce0_local;
reg    buffer_22_we0_local;
reg    buffer_22_ce0_local;
reg    buffer_21_we0_local;
reg    buffer_21_ce0_local;
reg    buffer_20_we0_local;
reg    buffer_20_ce0_local;
reg    buffer_19_we0_local;
reg    buffer_19_ce0_local;
reg    buffer_18_we0_local;
reg    buffer_18_ce0_local;
reg    buffer_17_we0_local;
reg    buffer_17_ce0_local;
reg    buffer_16_we0_local;
reg    buffer_16_ce0_local;
reg    buffer_15_we0_local;
reg    buffer_15_ce0_local;
reg    buffer_14_we0_local;
reg    buffer_14_ce0_local;
reg    buffer_13_we0_local;
reg    buffer_13_ce0_local;
reg    buffer_12_we0_local;
reg    buffer_12_ce0_local;
reg    buffer_11_we0_local;
reg    buffer_11_ce0_local;
reg    buffer_10_we0_local;
reg    buffer_10_ce0_local;
reg    buffer_9_we0_local;
reg    buffer_9_ce0_local;
reg    buffer_8_we0_local;
reg    buffer_8_ce0_local;
reg    buffer_7_we0_local;
reg    buffer_7_ce0_local;
reg    buffer_6_we0_local;
reg    buffer_6_ce0_local;
reg    buffer_5_we0_local;
reg    buffer_5_ce0_local;
reg    buffer_4_we0_local;
reg    buffer_4_ce0_local;
reg    buffer_3_we0_local;
reg    buffer_3_ce0_local;
reg    buffer_2_we0_local;
reg    buffer_2_ce0_local;
reg    buffer_1_we0_local;
reg    buffer_1_ce0_local;
reg    buffer_r_we0_local;
reg    buffer_r_ce0_local;
reg    buffer_31_we0_local;
reg    buffer_31_ce0_local;
wire   [2:0] trunc_ln2_fu_628_p4;
wire  signed [4:0] sext_ln37_fu_638_p1;
wire   [6:0] tmp_fu_678_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [0:0] tmp_fu_678_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 sizeIndex_fu_168 = 8'd0;
#0 j_1_fu_172 = 11'd0;
#0 ap_done_reg = 1'b0;
end

sha512Accel_bitselect_1ns_128ns_7ns_1_1_1 #(
    .DATAWIDTH( 128 ),
    .ADDRWIDTH( 7 ))
bitselect_1ns_128ns_7ns_1_1_1_U74(
    .din(size),
    .sel(tmp_fu_678_p2),
    .dout(tmp_fu_678_p3)
);

sha512Accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln38_fu_611_p2 == 1'd0)) begin
            j_1_fu_172 <= add_ln38_fu_787_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_172 <= 11'd896;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln38_fu_611_p2 == 1'd0)) begin
            sizeIndex_fu_168 <= sizeIndex_1_fu_793_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sizeIndex_fu_168 <= 8'd127;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln38_fu_611_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j = 11'd896;
    end else begin
        ap_sig_allocacmp_j = j_1_fu_172;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_sizeIndex_load = 8'd127;
    end else begin
        ap_sig_allocacmp_sizeIndex_load = sizeIndex_fu_168;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_sizeIndex_load_1 = 8'd127;
    end else begin
        ap_sig_allocacmp_sizeIndex_load_1 = sizeIndex_fu_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_10_ce0_local = 1'b1;
    end else begin
        buffer_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd10) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_10_we0_local = 1'b1;
    end else begin
        buffer_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_11_ce0_local = 1'b1;
    end else begin
        buffer_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd11) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_11_we0_local = 1'b1;
    end else begin
        buffer_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_12_ce0_local = 1'b1;
    end else begin
        buffer_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd12) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_12_we0_local = 1'b1;
    end else begin
        buffer_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_13_ce0_local = 1'b1;
    end else begin
        buffer_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd13) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_13_we0_local = 1'b1;
    end else begin
        buffer_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_14_ce0_local = 1'b1;
    end else begin
        buffer_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd14) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_14_we0_local = 1'b1;
    end else begin
        buffer_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_15_ce0_local = 1'b1;
    end else begin
        buffer_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd15) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_15_we0_local = 1'b1;
    end else begin
        buffer_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_16_ce0_local = 1'b1;
    end else begin
        buffer_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd16) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_16_we0_local = 1'b1;
    end else begin
        buffer_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_17_ce0_local = 1'b1;
    end else begin
        buffer_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd17) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_17_we0_local = 1'b1;
    end else begin
        buffer_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_18_ce0_local = 1'b1;
    end else begin
        buffer_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd18) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_18_we0_local = 1'b1;
    end else begin
        buffer_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_19_ce0_local = 1'b1;
    end else begin
        buffer_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd19) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_19_we0_local = 1'b1;
    end else begin
        buffer_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_1_ce0_local = 1'b1;
    end else begin
        buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd1) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_1_we0_local = 1'b1;
    end else begin
        buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_20_ce0_local = 1'b1;
    end else begin
        buffer_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd20) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_20_we0_local = 1'b1;
    end else begin
        buffer_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_21_ce0_local = 1'b1;
    end else begin
        buffer_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd21) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_21_we0_local = 1'b1;
    end else begin
        buffer_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_22_ce0_local = 1'b1;
    end else begin
        buffer_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd22) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_22_we0_local = 1'b1;
    end else begin
        buffer_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_23_ce0_local = 1'b1;
    end else begin
        buffer_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd23) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_23_we0_local = 1'b1;
    end else begin
        buffer_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_24_ce0_local = 1'b1;
    end else begin
        buffer_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd24) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_24_we0_local = 1'b1;
    end else begin
        buffer_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_25_ce0_local = 1'b1;
    end else begin
        buffer_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd25) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_25_we0_local = 1'b1;
    end else begin
        buffer_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_26_ce0_local = 1'b1;
    end else begin
        buffer_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd26) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_26_we0_local = 1'b1;
    end else begin
        buffer_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_27_ce0_local = 1'b1;
    end else begin
        buffer_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd27) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_27_we0_local = 1'b1;
    end else begin
        buffer_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_28_ce0_local = 1'b1;
    end else begin
        buffer_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd28) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_28_we0_local = 1'b1;
    end else begin
        buffer_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_29_ce0_local = 1'b1;
    end else begin
        buffer_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd29) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_29_we0_local = 1'b1;
    end else begin
        buffer_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_2_ce0_local = 1'b1;
    end else begin
        buffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd2) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_2_we0_local = 1'b1;
    end else begin
        buffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_30_ce0_local = 1'b1;
    end else begin
        buffer_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd30) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_30_we0_local = 1'b1;
    end else begin
        buffer_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_31_ce0_local = 1'b1;
    end else begin
        buffer_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd31) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_31_we0_local = 1'b1;
    end else begin
        buffer_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_3_ce0_local = 1'b1;
    end else begin
        buffer_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd3) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_3_we0_local = 1'b1;
    end else begin
        buffer_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_4_ce0_local = 1'b1;
    end else begin
        buffer_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd4) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_4_we0_local = 1'b1;
    end else begin
        buffer_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_5_ce0_local = 1'b1;
    end else begin
        buffer_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd5) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_5_we0_local = 1'b1;
    end else begin
        buffer_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_6_ce0_local = 1'b1;
    end else begin
        buffer_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd6) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_6_we0_local = 1'b1;
    end else begin
        buffer_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_7_ce0_local = 1'b1;
    end else begin
        buffer_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd7) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_7_we0_local = 1'b1;
    end else begin
        buffer_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_8_ce0_local = 1'b1;
    end else begin
        buffer_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd8) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_8_we0_local = 1'b1;
    end else begin
        buffer_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_9_ce0_local = 1'b1;
    end else begin
        buffer_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd9) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_9_we0_local = 1'b1;
    end else begin
        buffer_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_r_ce0_local = 1'b1;
    end else begin
        buffer_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln38_1_fu_624_p1 == 5'd0) & (icmp_ln38_fu_611_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        buffer_r_we0_local = 1'b1;
    end else begin
        buffer_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln38_fu_787_p2 = (ap_sig_allocacmp_j + 11'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_10_address0 = zext_ln37_fu_642_p1;

assign buffer_10_ce0 = buffer_10_ce0_local;

assign buffer_10_d0 = tmp_fu_678_p3;

assign buffer_10_we0 = buffer_10_we0_local;

assign buffer_11_address0 = zext_ln37_fu_642_p1;

assign buffer_11_ce0 = buffer_11_ce0_local;

assign buffer_11_d0 = tmp_fu_678_p3;

assign buffer_11_we0 = buffer_11_we0_local;

assign buffer_12_address0 = zext_ln37_fu_642_p1;

assign buffer_12_ce0 = buffer_12_ce0_local;

assign buffer_12_d0 = tmp_fu_678_p3;

assign buffer_12_we0 = buffer_12_we0_local;

assign buffer_13_address0 = zext_ln37_fu_642_p1;

assign buffer_13_ce0 = buffer_13_ce0_local;

assign buffer_13_d0 = tmp_fu_678_p3;

assign buffer_13_we0 = buffer_13_we0_local;

assign buffer_14_address0 = zext_ln37_fu_642_p1;

assign buffer_14_ce0 = buffer_14_ce0_local;

assign buffer_14_d0 = tmp_fu_678_p3;

assign buffer_14_we0 = buffer_14_we0_local;

assign buffer_15_address0 = zext_ln37_fu_642_p1;

assign buffer_15_ce0 = buffer_15_ce0_local;

assign buffer_15_d0 = tmp_fu_678_p3;

assign buffer_15_we0 = buffer_15_we0_local;

assign buffer_16_address0 = zext_ln37_fu_642_p1;

assign buffer_16_ce0 = buffer_16_ce0_local;

assign buffer_16_d0 = tmp_fu_678_p3;

assign buffer_16_we0 = buffer_16_we0_local;

assign buffer_17_address0 = zext_ln37_fu_642_p1;

assign buffer_17_ce0 = buffer_17_ce0_local;

assign buffer_17_d0 = tmp_fu_678_p3;

assign buffer_17_we0 = buffer_17_we0_local;

assign buffer_18_address0 = zext_ln37_fu_642_p1;

assign buffer_18_ce0 = buffer_18_ce0_local;

assign buffer_18_d0 = tmp_fu_678_p3;

assign buffer_18_we0 = buffer_18_we0_local;

assign buffer_19_address0 = zext_ln37_fu_642_p1;

assign buffer_19_ce0 = buffer_19_ce0_local;

assign buffer_19_d0 = tmp_fu_678_p3;

assign buffer_19_we0 = buffer_19_we0_local;

assign buffer_1_address0 = zext_ln37_fu_642_p1;

assign buffer_1_ce0 = buffer_1_ce0_local;

assign buffer_1_d0 = tmp_fu_678_p3;

assign buffer_1_we0 = buffer_1_we0_local;

assign buffer_20_address0 = zext_ln37_fu_642_p1;

assign buffer_20_ce0 = buffer_20_ce0_local;

assign buffer_20_d0 = tmp_fu_678_p3;

assign buffer_20_we0 = buffer_20_we0_local;

assign buffer_21_address0 = zext_ln37_fu_642_p1;

assign buffer_21_ce0 = buffer_21_ce0_local;

assign buffer_21_d0 = tmp_fu_678_p3;

assign buffer_21_we0 = buffer_21_we0_local;

assign buffer_22_address0 = zext_ln37_fu_642_p1;

assign buffer_22_ce0 = buffer_22_ce0_local;

assign buffer_22_d0 = tmp_fu_678_p3;

assign buffer_22_we0 = buffer_22_we0_local;

assign buffer_23_address0 = zext_ln37_fu_642_p1;

assign buffer_23_ce0 = buffer_23_ce0_local;

assign buffer_23_d0 = tmp_fu_678_p3;

assign buffer_23_we0 = buffer_23_we0_local;

assign buffer_24_address0 = zext_ln37_fu_642_p1;

assign buffer_24_ce0 = buffer_24_ce0_local;

assign buffer_24_d0 = tmp_fu_678_p3;

assign buffer_24_we0 = buffer_24_we0_local;

assign buffer_25_address0 = zext_ln37_fu_642_p1;

assign buffer_25_ce0 = buffer_25_ce0_local;

assign buffer_25_d0 = tmp_fu_678_p3;

assign buffer_25_we0 = buffer_25_we0_local;

assign buffer_26_address0 = zext_ln37_fu_642_p1;

assign buffer_26_ce0 = buffer_26_ce0_local;

assign buffer_26_d0 = tmp_fu_678_p3;

assign buffer_26_we0 = buffer_26_we0_local;

assign buffer_27_address0 = zext_ln37_fu_642_p1;

assign buffer_27_ce0 = buffer_27_ce0_local;

assign buffer_27_d0 = tmp_fu_678_p3;

assign buffer_27_we0 = buffer_27_we0_local;

assign buffer_28_address0 = zext_ln37_fu_642_p1;

assign buffer_28_ce0 = buffer_28_ce0_local;

assign buffer_28_d0 = tmp_fu_678_p3;

assign buffer_28_we0 = buffer_28_we0_local;

assign buffer_29_address0 = zext_ln37_fu_642_p1;

assign buffer_29_ce0 = buffer_29_ce0_local;

assign buffer_29_d0 = tmp_fu_678_p3;

assign buffer_29_we0 = buffer_29_we0_local;

assign buffer_2_address0 = zext_ln37_fu_642_p1;

assign buffer_2_ce0 = buffer_2_ce0_local;

assign buffer_2_d0 = tmp_fu_678_p3;

assign buffer_2_we0 = buffer_2_we0_local;

assign buffer_30_address0 = zext_ln37_fu_642_p1;

assign buffer_30_ce0 = buffer_30_ce0_local;

assign buffer_30_d0 = tmp_fu_678_p3;

assign buffer_30_we0 = buffer_30_we0_local;

assign buffer_31_address0 = zext_ln37_fu_642_p1;

assign buffer_31_ce0 = buffer_31_ce0_local;

assign buffer_31_d0 = tmp_fu_678_p3;

assign buffer_31_we0 = buffer_31_we0_local;

assign buffer_3_address0 = zext_ln37_fu_642_p1;

assign buffer_3_ce0 = buffer_3_ce0_local;

assign buffer_3_d0 = tmp_fu_678_p3;

assign buffer_3_we0 = buffer_3_we0_local;

assign buffer_4_address0 = zext_ln37_fu_642_p1;

assign buffer_4_ce0 = buffer_4_ce0_local;

assign buffer_4_d0 = tmp_fu_678_p3;

assign buffer_4_we0 = buffer_4_we0_local;

assign buffer_5_address0 = zext_ln37_fu_642_p1;

assign buffer_5_ce0 = buffer_5_ce0_local;

assign buffer_5_d0 = tmp_fu_678_p3;

assign buffer_5_we0 = buffer_5_we0_local;

assign buffer_6_address0 = zext_ln37_fu_642_p1;

assign buffer_6_ce0 = buffer_6_ce0_local;

assign buffer_6_d0 = tmp_fu_678_p3;

assign buffer_6_we0 = buffer_6_we0_local;

assign buffer_7_address0 = zext_ln37_fu_642_p1;

assign buffer_7_ce0 = buffer_7_ce0_local;

assign buffer_7_d0 = tmp_fu_678_p3;

assign buffer_7_we0 = buffer_7_we0_local;

assign buffer_8_address0 = zext_ln37_fu_642_p1;

assign buffer_8_ce0 = buffer_8_ce0_local;

assign buffer_8_d0 = tmp_fu_678_p3;

assign buffer_8_we0 = buffer_8_we0_local;

assign buffer_9_address0 = zext_ln37_fu_642_p1;

assign buffer_9_ce0 = buffer_9_ce0_local;

assign buffer_9_d0 = tmp_fu_678_p3;

assign buffer_9_we0 = buffer_9_we0_local;

assign buffer_r_address0 = zext_ln37_fu_642_p1;

assign buffer_r_ce0 = buffer_r_ce0_local;

assign buffer_r_d0 = tmp_fu_678_p3;

assign buffer_r_we0 = buffer_r_we0_local;

assign icmp_ln38_fu_611_p2 = ((ap_sig_allocacmp_j == 11'd1024) ? 1'b1 : 1'b0);

assign sext_ln37_fu_638_p1 = $signed(trunc_ln2_fu_628_p4);

assign sizeIndex_1_fu_793_p2 = ($signed(ap_sig_allocacmp_sizeIndex_load) + $signed(8'd255));

assign tmp_fu_678_p2 = ap_sig_allocacmp_sizeIndex_load_1[6:0];

assign trunc_ln2_fu_628_p4 = {{ap_sig_allocacmp_j[7:5]}};

assign trunc_ln38_1_fu_624_p1 = ap_sig_allocacmp_j[4:0];

assign zext_ln37_fu_642_p1 = $unsigned(sext_ln37_fu_638_p1);

endmodule //sha512Accel_sha512Accel_Pipeline_VITIS_LOOP_38_4
