// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="wGenerator_wGenerator,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7s6-cpga196-2I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.329000,HLS_SYN_LAT=169,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=149,HLS_SYN_LUT=572,HLS_VERSION=2025_1}" *)

module wGenerator (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        win_address0,
        win_ce0,
        win_q0,
        wout_address0,
        wout_ce0,
        wout_we0,
        wout_d0,
        wout_q0,
        wout_address1,
        wout_ce1,
        wout_q1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] win_address0;
output   win_ce0;
input  [31:0] win_q0;
output  [5:0] wout_address0;
output   wout_ce0;
output   wout_we0;
output  [31:0] wout_d0;
input  [31:0] wout_q0;
output  [5:0] wout_address1;
output   wout_ce1;
input  [31:0] wout_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] wout_address0;
reg wout_ce0;
reg wout_we0;
reg[31:0] wout_d0;
reg wout_ce1;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_done;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_idle;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_ready;
wire   [3:0] grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_win_address0;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_win_ce0;
wire   [5:0] grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_address0;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_ce0;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_we0;
wire   [31:0] grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_d0;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_done;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_idle;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_ready;
wire   [5:0] grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_address0;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_ce0;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_we0;
wire   [31:0] grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_d0;
wire   [5:0] grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_address1;
wire    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_ce1;
reg    grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start_reg = 1'b0;
#0 grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start_reg = 1'b0;
end

wGenerator_wGenerator_Pipeline_VITIS_LOOP_7_1 grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start),
    .ap_done(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_done),
    .ap_idle(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_idle),
    .ap_ready(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_ready),
    .win_address0(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_win_address0),
    .win_ce0(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_win_ce0),
    .win_q0(win_q0),
    .wout_address0(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_address0),
    .wout_ce0(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_ce0),
    .wout_we0(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_we0),
    .wout_d0(grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_d0)
);

wGenerator_wGenerator_Pipeline_VITIS_LOOP_10_2 grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start),
    .ap_done(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_done),
    .ap_idle(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_idle),
    .ap_ready(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_ready),
    .wout_address0(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_address0),
    .wout_ce0(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_ce0),
    .wout_we0(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_we0),
    .wout_d0(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_d0),
    .wout_q0(wout_q0),
    .wout_address1(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_address1),
    .wout_ce1(grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_ce1),
    .wout_q1(wout_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_ready == 1'b1)) begin
            grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start_reg <= 1'b1;
        end else if ((grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_ready == 1'b1)) begin
            grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        wout_address0 = grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        wout_address0 = grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_address0;
    end else begin
        wout_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        wout_ce0 = grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        wout_ce0 = grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_ce0;
    end else begin
        wout_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        wout_ce1 = grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_ce1;
    end else begin
        wout_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        wout_d0 = grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        wout_d0 = grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_d0;
    end else begin
        wout_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        wout_we0 = grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        wout_we0 = grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_wout_we0;
    end else begin
        wout_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start = grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_ap_start_reg;

assign grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start = grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_ap_start_reg;

assign win_address0 = grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_win_address0;

assign win_ce0 = grp_wGenerator_Pipeline_VITIS_LOOP_7_1_fu_24_win_ce0;

assign wout_address1 = grp_wGenerator_Pipeline_VITIS_LOOP_10_2_fu_32_wout_address1;

endmodule //wGenerator
