// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_27_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        wvars_load_7,
        wvars_load_6,
        wvars_load_5,
        wvars_load_4,
        wvars_load_3,
        wvars_load_2,
        wvars_load_1,
        wvars_load,
        wValues_address0,
        wValues_ce0,
        wValues_q0,
        thr_add562568_out,
        thr_add562568_out_ap_vld,
        add_i26_i251347_out,
        add_i26_i251347_out_ap_vld,
        thr_add56256_out,
        thr_add56256_out_ap_vld,
        thr_add5625_out,
        thr_add5625_out_ap_vld,
        add_i26_i25134_out,
        add_i26_i25134_out_ap_vld,
        add_i26_i2513_out,
        add_i26_i2513_out_ap_vld,
        thr_add562_out,
        thr_add562_out_ap_vld,
        add_i26_i251_out,
        add_i26_i251_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] wvars_load_7;
input  [63:0] wvars_load_6;
input  [63:0] wvars_load_5;
input  [63:0] wvars_load_4;
input  [63:0] wvars_load_3;
input  [63:0] wvars_load_2;
input  [63:0] wvars_load_1;
input  [63:0] wvars_load;
output  [6:0] wValues_address0;
output   wValues_ce0;
input  [63:0] wValues_q0;
output  [63:0] thr_add562568_out;
output   thr_add562568_out_ap_vld;
output  [63:0] add_i26_i251347_out;
output   add_i26_i251347_out_ap_vld;
output  [63:0] thr_add56256_out;
output   thr_add56256_out_ap_vld;
output  [63:0] thr_add5625_out;
output   thr_add5625_out_ap_vld;
output  [63:0] add_i26_i25134_out;
output   add_i26_i25134_out_ap_vld;
output  [63:0] add_i26_i2513_out;
output   add_i26_i2513_out_ap_vld;
output  [63:0] thr_add562_out;
output   thr_add562_out_ap_vld;
output  [63:0] add_i26_i251_out;
output   add_i26_i251_out_ap_vld;

reg ap_idle;
reg thr_add562568_out_ap_vld;
reg add_i26_i251347_out_ap_vld;
reg thr_add56256_out_ap_vld;
reg thr_add5625_out_ap_vld;
reg add_i26_i25134_out_ap_vld;
reg add_i26_i2513_out_ap_vld;
reg thr_add562_out_ap_vld;
reg add_i26_i251_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln27_reg_715;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] kValues_address0;
wire   [63:0] kValues_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln27_fu_320_p2;
reg   [0:0] icmp_ln27_reg_715_pp0_iter1_reg;
reg   [63:0] add_i26_i251_load_reg_729;
wire    ap_block_pp0_stage1_11001;
reg   [63:0] add_i26_i25134_load_reg_740;
wire   [63:0] or_ln13_fu_370_p2;
reg   [63:0] or_ln13_reg_746;
wire   [63:0] add_ln13_fu_376_p2;
reg   [63:0] add_ln13_reg_751;
reg   [63:0] thr_add562_load_reg_756;
reg   [63:0] thr_add56256_load_reg_767;
reg   [63:0] thr_add5625_load_reg_774;
wire   [63:0] t1_fu_488_p2;
reg   [63:0] t1_reg_780;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln27_fu_332_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] i_fu_106;
wire   [6:0] add_ln27_fu_326_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_3;
reg   [63:0] add_i26_i2513_fu_110;
wire    ap_block_pp0_stage1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_idle_pp0_0to0;
reg   [63:0] thr_add5625_fu_114;
reg   [63:0] thr_add562_fu_118;
wire   [63:0] add_ln15_2_fu_607_p2;
reg   [63:0] add_i26_i251347_fu_122;
reg   [63:0] thr_add562568_fu_126;
reg   [63:0] add_i26_i251_fu_130;
wire   [63:0] add_ln19_fu_613_p2;
reg   [63:0] ap_sig_allocacmp_add_i26_i251_load;
reg   [63:0] add_i26_i25134_fu_134;
reg   [63:0] thr_add56256_fu_138;
wire    ap_block_pp0_stage0_01001;
reg    kValues_ce0_local;
reg    wValues_ce0_local;
wire   [63:0] xor_ln13_fu_352_p2;
wire   [63:0] and_ln13_fu_358_p2;
wire   [63:0] and_ln13_1_fu_364_p2;
wire   [13:0] trunc_ln17_fu_415_p1;
wire   [49:0] lshr_ln5_fu_406_p4;
wire   [17:0] trunc_ln18_fu_427_p1;
wire   [45:0] lshr_ln6_fu_418_p4;
wire   [40:0] trunc_ln19_fu_439_p1;
wire   [22:0] lshr_ln_fu_430_p4;
wire   [63:0] or_ln13_1_fu_450_p3;
wire   [63:0] or_ln13_3_fu_458_p3;
wire   [63:0] xor_ln13_1_fu_466_p2;
wire   [63:0] or_ln2_fu_442_p3;
wire   [63:0] xor_ln13_2_fu_472_p2;
wire   [63:0] add_ln13_2_fu_483_p2;
wire   [63:0] add_ln13_1_fu_478_p2;
wire   [63:0] or_ln15_fu_547_p2;
wire   [27:0] trunc_ln7_fu_520_p1;
wire   [35:0] lshr_ln7_fu_511_p4;
wire   [33:0] trunc_ln8_fu_532_p1;
wire   [29:0] lshr_ln8_fu_523_p4;
wire   [63:0] and_ln15_fu_551_p2;
wire   [63:0] and_ln15_1_fu_556_p2;
wire   [38:0] trunc_ln9_fu_544_p1;
wire   [24:0] lshr_ln9_fu_535_p4;
wire   [63:0] or_ln15_2_fu_568_p3;
wire   [63:0] or_ln15_4_fu_582_p3;
wire   [63:0] xor_ln15_fu_590_p2;
wire   [63:0] or_ln15_1_fu_560_p3;
wire   [63:0] or_ln15_3_fu_576_p2;
wire   [63:0] add_ln15_fu_602_p2;
wire   [63:0] xor_ln15_1_fu_596_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_106 = 7'd0;
#0 add_i26_i2513_fu_110 = 64'd0;
#0 thr_add5625_fu_114 = 64'd0;
#0 thr_add562_fu_118 = 64'd0;
#0 add_i26_i251347_fu_122 = 64'd0;
#0 thr_add562568_fu_126 = 64'd0;
#0 add_i26_i251_fu_130 = 64'd0;
#0 add_i26_i25134_fu_134 = 64'd0;
#0 thr_add56256_fu_138 = 64'd0;
#0 ap_done_reg = 1'b0;
end

sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_27_2_kValues_ROM_AUTO_1R #(
    .DataWidth( 64 ),
    .AddressRange( 80 ),
    .AddressWidth( 7 ))
kValues_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kValues_address0),
    .ce0(kValues_ce0_local),
    .q0(kValues_q0)
);

sha512Accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add_i26_i251347_fu_122 <= wvars_load_6;
        end else if (((icmp_ln27_reg_715 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            add_i26_i251347_fu_122 <= add_i26_i25134_load_reg_740;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        add_i26_i25134_fu_134 <= wvars_load_3;
    end else if (((icmp_ln27_reg_715 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_i26_i25134_fu_134 <= add_i26_i2513_fu_110;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        add_i26_i2513_fu_110 <= wvars_load_2;
    end else if (((icmp_ln27_reg_715 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_i26_i2513_fu_110 <= ap_sig_allocacmp_add_i26_i251_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        add_i26_i251_fu_130 <= wvars_load;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln27_reg_715_pp0_iter1_reg == 1'd0))) begin
        add_i26_i251_fu_130 <= add_ln19_fu_613_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln27_fu_320_p2 == 1'd0))) begin
            i_fu_106 <= add_ln27_fu_326_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_106 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        thr_add562568_fu_126 <= wvars_load_7;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln27_reg_715_pp0_iter1_reg == 1'd0))) begin
        thr_add562568_fu_126 <= thr_add56256_load_reg_767;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            thr_add56256_fu_138 <= wvars_load_5;
        end else if (((icmp_ln27_reg_715 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            thr_add56256_fu_138 <= thr_add5625_fu_114;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            thr_add5625_fu_114 <= wvars_load_4;
        end else if (((icmp_ln27_reg_715 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            thr_add5625_fu_114 <= thr_add562_fu_118;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        thr_add562_fu_118 <= wvars_load_1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln27_reg_715_pp0_iter1_reg == 1'd0))) begin
        thr_add562_fu_118 <= add_ln15_2_fu_607_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_i26_i25134_load_reg_740 <= add_i26_i25134_fu_134;
        add_i26_i251_load_reg_729 <= ap_sig_allocacmp_add_i26_i251_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln13_reg_751 <= add_ln13_fu_376_p2;
        or_ln13_reg_746 <= or_ln13_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln27_reg_715 <= icmp_ln27_fu_320_p2;
        icmp_ln27_reg_715_pp0_iter1_reg <= icmp_ln27_reg_715;
        t1_reg_780 <= t1_fu_488_p2;
        thr_add5625_load_reg_774 <= thr_add5625_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        thr_add56256_load_reg_767 <= thr_add56256_fu_138;
        thr_add562_load_reg_756 <= thr_add562_fu_118;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        add_i26_i251347_out_ap_vld = 1'b1;
    end else begin
        add_i26_i251347_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        add_i26_i25134_out_ap_vld = 1'b1;
    end else begin
        add_i26_i25134_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        add_i26_i2513_out_ap_vld = 1'b1;
    end else begin
        add_i26_i2513_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        add_i26_i251_out_ap_vld = 1'b1;
    end else begin
        add_i26_i251_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln27_reg_715_pp0_iter1_reg == 1'd0))) begin
        ap_sig_allocacmp_add_i26_i251_load = add_ln19_fu_613_p2;
    end else begin
        ap_sig_allocacmp_add_i26_i251_load = add_i26_i251_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kValues_ce0_local = 1'b1;
    end else begin
        kValues_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        thr_add562568_out_ap_vld = 1'b1;
    end else begin
        thr_add562568_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        thr_add56256_out_ap_vld = 1'b1;
    end else begin
        thr_add56256_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        thr_add5625_out_ap_vld = 1'b1;
    end else begin
        thr_add5625_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_715 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        thr_add562_out_ap_vld = 1'b1;
    end else begin
        thr_add562_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wValues_ce0_local = 1'b1;
    end else begin
        wValues_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i26_i251347_out = add_i26_i251347_fu_122;

assign add_i26_i25134_out = add_i26_i25134_load_reg_740;

assign add_i26_i2513_out = add_i26_i2513_fu_110;

assign add_i26_i251_out = add_i26_i251_load_reg_729;

assign add_ln13_1_fu_478_p2 = (add_ln13_reg_751 + add_i26_i251347_fu_122);

assign add_ln13_2_fu_483_p2 = (or_ln13_reg_746 + xor_ln13_2_fu_472_p2);

assign add_ln13_fu_376_p2 = (kValues_q0 + wValues_q0);

assign add_ln15_2_fu_607_p2 = (add_ln15_fu_602_p2 + xor_ln15_1_fu_596_p2);

assign add_ln15_fu_602_p2 = (t1_reg_780 + or_ln15_3_fu_576_p2);

assign add_ln19_fu_613_p2 = (t1_reg_780 + thr_add562568_fu_126);

assign add_ln27_fu_326_p2 = (ap_sig_allocacmp_i_3 + 7'd1);

assign and_ln13_1_fu_364_p2 = (ap_sig_allocacmp_add_i26_i251_load & add_i26_i2513_fu_110);

assign and_ln13_fu_358_p2 = (xor_ln13_fu_352_p2 & add_i26_i25134_fu_134);

assign and_ln15_1_fu_556_p2 = (thr_add5625_load_reg_774 & thr_add56256_load_reg_767);

assign and_ln15_fu_551_p2 = (thr_add562_load_reg_756 & or_ln15_fu_547_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign icmp_ln27_fu_320_p2 = ((ap_sig_allocacmp_i_3 == 7'd80) ? 1'b1 : 1'b0);

assign kValues_address0 = zext_ln27_fu_332_p1;

assign lshr_ln5_fu_406_p4 = {{add_i26_i251_load_reg_729[63:14]}};

assign lshr_ln6_fu_418_p4 = {{add_i26_i251_load_reg_729[63:18]}};

assign lshr_ln7_fu_511_p4 = {{thr_add562_load_reg_756[63:28]}};

assign lshr_ln8_fu_523_p4 = {{thr_add562_load_reg_756[63:34]}};

assign lshr_ln9_fu_535_p4 = {{thr_add562_load_reg_756[63:39]}};

assign lshr_ln_fu_430_p4 = {{add_i26_i251_load_reg_729[63:41]}};

assign or_ln13_1_fu_450_p3 = {{trunc_ln18_fu_427_p1}, {lshr_ln6_fu_418_p4}};

assign or_ln13_3_fu_458_p3 = {{trunc_ln19_fu_439_p1}, {lshr_ln_fu_430_p4}};

assign or_ln13_fu_370_p2 = (and_ln13_fu_358_p2 | and_ln13_1_fu_364_p2);

assign or_ln15_1_fu_560_p3 = {{trunc_ln7_fu_520_p1}, {lshr_ln7_fu_511_p4}};

assign or_ln15_2_fu_568_p3 = {{trunc_ln8_fu_532_p1}, {lshr_ln8_fu_523_p4}};

assign or_ln15_3_fu_576_p2 = (and_ln15_fu_551_p2 | and_ln15_1_fu_556_p2);

assign or_ln15_4_fu_582_p3 = {{trunc_ln9_fu_544_p1}, {lshr_ln9_fu_535_p4}};

assign or_ln15_fu_547_p2 = (thr_add5625_load_reg_774 | thr_add56256_load_reg_767);

assign or_ln2_fu_442_p3 = {{trunc_ln17_fu_415_p1}, {lshr_ln5_fu_406_p4}};

assign t1_fu_488_p2 = (add_ln13_2_fu_483_p2 + add_ln13_1_fu_478_p2);

assign thr_add562568_out = thr_add562568_fu_126;

assign thr_add56256_out = thr_add56256_fu_138;

assign thr_add5625_out = thr_add5625_fu_114;

assign thr_add562_out = thr_add562_fu_118;

assign trunc_ln17_fu_415_p1 = add_i26_i251_load_reg_729[13:0];

assign trunc_ln18_fu_427_p1 = add_i26_i251_load_reg_729[17:0];

assign trunc_ln19_fu_439_p1 = add_i26_i251_load_reg_729[40:0];

assign trunc_ln7_fu_520_p1 = thr_add562_load_reg_756[27:0];

assign trunc_ln8_fu_532_p1 = thr_add562_load_reg_756[33:0];

assign trunc_ln9_fu_544_p1 = thr_add562_load_reg_756[38:0];

assign wValues_address0 = zext_ln27_fu_332_p1;

assign wValues_ce0 = wValues_ce0_local;

assign xor_ln13_1_fu_466_p2 = (or_ln13_3_fu_458_p3 ^ or_ln13_1_fu_450_p3);

assign xor_ln13_2_fu_472_p2 = (xor_ln13_1_fu_466_p2 ^ or_ln2_fu_442_p3);

assign xor_ln13_fu_352_p2 = (ap_sig_allocacmp_add_i26_i251_load ^ 64'd18446744073709551615);

assign xor_ln15_1_fu_596_p2 = (xor_ln15_fu_590_p2 ^ or_ln15_1_fu_560_p3);

assign xor_ln15_fu_590_p2 = (or_ln15_4_fu_582_p3 ^ or_ln15_2_fu_568_p3);

assign zext_ln27_fu_332_p1 = ap_sig_allocacmp_i_3;

endmodule //sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_27_2
