-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sha512Accel_chunkProcessor is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    message_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    message_ce0 : OUT STD_LOGIC;
    message_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of sha512Accel_chunkProcessor is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal wvars_addr_reg_282 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal wvars_addr_1_reg_287 : STD_LOGIC_VECTOR (2 downto 0);
    signal wvars_addr_2_reg_292 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal wvars_addr_3_reg_297 : STD_LOGIC_VECTOR (2 downto 0);
    signal wvars_load_reg_302 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_load_1_reg_307 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_addr_4_reg_312 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal wvars_addr_5_reg_317 : STD_LOGIC_VECTOR (2 downto 0);
    signal wvars_load_2_reg_322 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_load_3_reg_327 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_addr_6_reg_332 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal wvars_addr_7_reg_337 : STD_LOGIC_VECTOR (2 downto 0);
    signal wvars_load_4_reg_342 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_load_5_reg_347 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_load_6_reg_352 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal wvars_load_7_reg_357 : STD_LOGIC_VECTOR (63 downto 0);
    signal wValues_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal wValues_ce0 : STD_LOGIC;
    signal wValues_we0 : STD_LOGIC;
    signal wValues_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal wValues_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal wValues_ce1 : STD_LOGIC;
    signal wValues_q1 : STD_LOGIC_VECTOR (63 downto 0);
    signal wValues_ce2 : STD_LOGIC;
    signal wValues_q2 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal wvars_ce0 : STD_LOGIC;
    signal wvars_we0 : STD_LOGIC;
    signal wvars_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_q0 : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_q1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_done : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_idle : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_ready : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_message_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_message_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_we0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_done : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_idle : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_ready : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_we0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_idle : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_ready : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_we0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce1 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce2 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_done : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_idle : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_ready : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562568_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562568_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251347_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251347_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add56256_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add56256_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add5625_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add5625_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i25134_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i25134_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i2513_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i2513_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251_out_ap_vld : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_idle : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_ready : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_ce0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_we0 : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start_reg : STD_LOGIC := '0';
    signal wvars_we0_out : STD_LOGIC;
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start_reg : STD_LOGIC := '0';
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal wvars_ce1_local : STD_LOGIC;
    signal wvars_address1_local : STD_LOGIC_VECTOR (2 downto 0);
    signal wvars_ce0_local : STD_LOGIC;
    signal wvars_address0_local : STD_LOGIC_VECTOR (2 downto 0);
    signal wvars_we1_local : STD_LOGIC;
    signal wvars_d1_local : STD_LOGIC_VECTOR (63 downto 0);
    signal wvars_we0_local : STD_LOGIC;
    signal wvars_d0_local : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_8_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        message_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        message_ce0 : OUT STD_LOGIC;
        message_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        wValues_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        wValues_ce0 : OUT STD_LOGIC;
        wValues_we0 : OUT STD_LOGIC;
        wValues_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_24_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        wvars_ce0 : OUT STD_LOGIC;
        wvars_we0 : OUT STD_LOGIC;
        wvars_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_11_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        wValues_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        wValues_ce0 : OUT STD_LOGIC;
        wValues_we0 : OUT STD_LOGIC;
        wValues_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        wValues_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        wValues_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        wValues_ce1 : OUT STD_LOGIC;
        wValues_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        wValues_address2 : OUT STD_LOGIC_VECTOR (6 downto 0);
        wValues_ce2 : OUT STD_LOGIC;
        wValues_q2 : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_27_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        wvars_load_7 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_load_6 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_load_5 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_load_4 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_load_3 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_load_2 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_load_1 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_load : IN STD_LOGIC_VECTOR (63 downto 0);
        wValues_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        wValues_ce0 : OUT STD_LOGIC;
        wValues_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        thr_add562568_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        thr_add562568_out_ap_vld : OUT STD_LOGIC;
        add_i26_i251347_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_i26_i251347_out_ap_vld : OUT STD_LOGIC;
        thr_add56256_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        thr_add56256_out_ap_vld : OUT STD_LOGIC;
        thr_add5625_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        thr_add5625_out_ap_vld : OUT STD_LOGIC;
        add_i26_i25134_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_i26_i25134_out_ap_vld : OUT STD_LOGIC;
        add_i26_i2513_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_i26_i2513_out_ap_vld : OUT STD_LOGIC;
        thr_add562_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        thr_add562_out_ap_vld : OUT STD_LOGIC;
        add_i26_i251_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        add_i26_i251_out_ap_vld : OUT STD_LOGIC );
    end component;


    component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_34_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        wvars_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        wvars_ce0 : OUT STD_LOGIC;
        wvars_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sha512Accel_chunkProcessor_wValues_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component sha512Accel_chunkProcessor_wvars_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (63 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (63 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    wValues_U : component sha512Accel_chunkProcessor_wValues_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 80,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => wValues_address0,
        ce0 => wValues_ce0,
        we0 => wValues_we0,
        d0 => wValues_d0,
        q0 => wValues_q0,
        address1 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address1,
        ce1 => wValues_ce1,
        q1 => wValues_q1,
        address2 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address2,
        ce2 => wValues_ce2,
        q2 => wValues_q2);

    wvars_U : component sha512Accel_chunkProcessor_wvars_RAM_AUTO_1R1W
    generic map (
        DataWidth => 64,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => wvars_address0,
        ce0 => wvars_ce0,
        we0 => wvars_we0,
        d0 => wvars_d0,
        q0 => wvars_q0,
        address1 => wvars_address1_local,
        ce1 => wvars_ce1_local,
        we1 => wvars_we1_local,
        d1 => wvars_d1_local,
        q1 => wvars_q1);

    grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147 : component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_8_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start,
        ap_done => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_done,
        ap_idle => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_idle,
        ap_ready => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_ready,
        message_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_message_address0,
        message_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_message_ce0,
        message_q0 => message_q0,
        wValues_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_address0,
        wValues_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_ce0,
        wValues_we0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_we0,
        wValues_d0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_d0);

    grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155 : component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_24_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start,
        ap_done => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_done,
        ap_idle => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_idle,
        ap_ready => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_ready,
        input_r_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_address0,
        input_r_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_ce0,
        input_r_q0 => input_r_q0,
        wvars_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_address0,
        wvars_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_ce0,
        wvars_we0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_we0,
        wvars_d0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_d0);

    grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163 : component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_11_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start,
        ap_done => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done,
        ap_idle => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_idle,
        ap_ready => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_ready,
        wValues_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address0,
        wValues_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce0,
        wValues_we0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_we0,
        wValues_d0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_d0,
        wValues_q0 => wValues_q0,
        wValues_address1 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address1,
        wValues_ce1 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce1,
        wValues_q1 => wValues_q1,
        wValues_address2 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address2,
        wValues_ce2 => grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce2,
        wValues_q2 => wValues_q2);

    grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168 : component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_27_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start,
        ap_done => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_done,
        ap_idle => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_idle,
        ap_ready => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_ready,
        wvars_load_7 => wvars_load_7_reg_357,
        wvars_load_6 => wvars_load_6_reg_352,
        wvars_load_5 => wvars_load_5_reg_347,
        wvars_load_4 => wvars_load_4_reg_342,
        wvars_load_3 => wvars_load_3_reg_327,
        wvars_load_2 => wvars_load_2_reg_322,
        wvars_load_1 => wvars_load_1_reg_307,
        wvars_load => wvars_load_reg_302,
        wValues_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_address0,
        wValues_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_ce0,
        wValues_q0 => wValues_q0,
        thr_add562568_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562568_out,
        thr_add562568_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562568_out_ap_vld,
        add_i26_i251347_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251347_out,
        add_i26_i251347_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251347_out_ap_vld,
        thr_add56256_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add56256_out,
        thr_add56256_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add56256_out_ap_vld,
        thr_add5625_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add5625_out,
        thr_add5625_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add5625_out_ap_vld,
        add_i26_i25134_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i25134_out,
        add_i26_i25134_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i25134_out_ap_vld,
        add_i26_i2513_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i2513_out,
        add_i26_i2513_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i2513_out_ap_vld,
        thr_add562_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562_out,
        thr_add562_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562_out_ap_vld,
        add_i26_i251_out => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251_out,
        add_i26_i251_out_ap_vld => grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251_out_ap_vld);

    grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193 : component sha512Accel_chunkProcessor_Pipeline_VITIS_LOOP_34_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start,
        ap_done => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done,
        ap_idle => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_idle,
        ap_ready => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_ready,
        input_r_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_address0,
        input_r_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_ce0,
        input_r_q0 => input_r_q0,
        wvars_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_address0,
        wvars_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_ce0,
        wvars_q0 => wvars_q0,
        output_r_address0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_address0,
        output_r_ce0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_ce0,
        output_r_we0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_we0,
        output_r_d0 => grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_ready = ap_const_logic_1)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_ready = ap_const_logic_1)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_ready = ap_const_logic_1)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_ready = ap_const_logic_1)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_ready = ap_const_logic_1)) then 
                    grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                wvars_load_1_reg_307 <= wvars_q0;
                wvars_load_reg_302 <= wvars_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                wvars_load_2_reg_322 <= wvars_q1;
                wvars_load_3_reg_327 <= wvars_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                wvars_load_4_reg_342 <= wvars_q1;
                wvars_load_5_reg_347 <= wvars_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                wvars_load_6_reg_352 <= wvars_q1;
                wvars_load_7_reg_357 <= wvars_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_done, grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state8, ap_CS_fsm_state14, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done)
    begin
        if ((grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done)
    begin
        if ((grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_done)
    begin
        if ((grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state2_on_subcall_done_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_done, grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_done = ap_const_logic_0) or (grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done, ap_CS_fsm_state14)
    begin
        if ((((grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done, ap_CS_fsm_state14)
    begin
        if (((grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start <= grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_start_reg;
    grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start <= grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_ap_start_reg;
    grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_ap_start_reg;
    grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_ap_start_reg;
    grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start <= grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_ap_start_reg;

    input_r_address0_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_address0, grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_address0, ap_CS_fsm_state2, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            input_r_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_r_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_address0;
        else 
            input_r_address0 <= "XXX";
        end if; 
    end process;


    input_r_ce0_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_ce0, grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_ce0, ap_CS_fsm_state2, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            input_r_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_input_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_r_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_input_r_ce0;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    message_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_message_address0;
    message_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_message_ce0;
    output_r_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_address0;
    output_r_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_ce0;
    output_r_d0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_d0;
    output_r_we0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_output_r_we0;

    wValues_address0_assign_proc : process(ap_CS_fsm_state4, grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_address0, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address0, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_address0, ap_CS_fsm_state2, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            wValues_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wValues_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wValues_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_address0;
        else 
            wValues_address0 <= "XXXXXXX";
        end if; 
    end process;


    wValues_ce0_assign_proc : process(ap_CS_fsm_state4, grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_ce0, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce0, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_ce0, ap_CS_fsm_state2, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            wValues_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_wValues_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wValues_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wValues_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_ce0;
        else 
            wValues_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    wValues_ce1_assign_proc : process(ap_CS_fsm_state4, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wValues_ce1 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce1;
        else 
            wValues_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    wValues_ce2_assign_proc : process(ap_CS_fsm_state4, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wValues_ce2 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_ce2;
        else 
            wValues_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    wValues_d0_assign_proc : process(ap_CS_fsm_state4, grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_d0, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_d0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wValues_d0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wValues_d0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_d0;
        else 
            wValues_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    wValues_we0_assign_proc : process(ap_CS_fsm_state4, grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_we0, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wValues_we0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_wValues_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wValues_we0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147_wValues_we0;
        else 
            wValues_we0 <= ap_const_logic_0;
        end if; 
    end process;

    wvars_addr_1_reg_287 <= ap_const_lv64_4(3 - 1 downto 0);
    wvars_addr_2_reg_292 <= ap_const_lv64_5(3 - 1 downto 0);
    wvars_addr_3_reg_297 <= ap_const_lv64_6(3 - 1 downto 0);
    wvars_addr_4_reg_312 <= ap_const_lv64_1(3 - 1 downto 0);
    wvars_addr_5_reg_317 <= ap_const_lv64_2(3 - 1 downto 0);
    wvars_addr_6_reg_332 <= ap_const_lv64_7(3 - 1 downto 0);
    wvars_addr_7_reg_337 <= ap_const_lv64_3(3 - 1 downto 0);
    wvars_addr_reg_282 <= ap_const_lv64_0(3 - 1 downto 0);

    wvars_address0_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_address0, grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_address0, ap_CS_fsm_state2, ap_CS_fsm_state14, wvars_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            wvars_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wvars_address0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_address0;
        else 
            wvars_address0 <= wvars_address0_local;
        end if; 
    end process;


    wvars_address0_local_assign_proc : process(wvars_addr_reg_282, ap_CS_fsm_state3, ap_CS_fsm_state4, wvars_addr_3_reg_297, ap_CS_fsm_state5, wvars_addr_5_reg_317, ap_CS_fsm_state6, wvars_addr_7_reg_337, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            wvars_address0_local <= wvars_addr_7_reg_337;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            wvars_address0_local <= wvars_addr_5_reg_317;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            wvars_address0_local <= wvars_addr_3_reg_297;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            wvars_address0_local <= wvars_addr_reg_282;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            wvars_address0_local <= ap_const_lv64_3(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            wvars_address0_local <= ap_const_lv64_2(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wvars_address0_local <= ap_const_lv64_6(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            wvars_address0_local <= ap_const_lv64_0(3 - 1 downto 0);
        else 
            wvars_address0_local <= "XXX";
        end if; 
    end process;


    wvars_address1_local_assign_proc : process(ap_CS_fsm_state3, wvars_addr_1_reg_287, wvars_addr_2_reg_292, ap_CS_fsm_state4, wvars_addr_4_reg_312, ap_CS_fsm_state5, wvars_addr_6_reg_332, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            wvars_address1_local <= wvars_addr_6_reg_332;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            wvars_address1_local <= wvars_addr_4_reg_312;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            wvars_address1_local <= wvars_addr_2_reg_292;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            wvars_address1_local <= wvars_addr_1_reg_287;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            wvars_address1_local <= ap_const_lv64_7(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            wvars_address1_local <= ap_const_lv64_1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            wvars_address1_local <= ap_const_lv64_5(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            wvars_address1_local <= ap_const_lv64_4(3 - 1 downto 0);
        else 
            wvars_address1_local <= "XXX";
        end if; 
    end process;


    wvars_ce0_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_ce0, grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_ce0, ap_CS_fsm_state2, ap_CS_fsm_state14, wvars_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            wvars_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193_wvars_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wvars_ce0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_ce0;
        else 
            wvars_ce0 <= wvars_ce0_local;
        end if; 
    end process;


    wvars_ce0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done = ap_const_logic_1)))) then 
            wvars_ce0_local <= ap_const_logic_1;
        else 
            wvars_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    wvars_ce1_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163_ap_done = ap_const_logic_1)))) then 
            wvars_ce1_local <= ap_const_logic_1;
        else 
            wvars_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    wvars_d0_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_d0, ap_CS_fsm_state2, wvars_d0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wvars_d0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_d0;
        else 
            wvars_d0 <= wvars_d0_local;
        end if; 
    end process;


    wvars_d0_local_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562568_out, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add56256_out, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i25134_out, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562_out, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            wvars_d0_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562568_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            wvars_d0_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add56256_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            wvars_d0_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i25134_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            wvars_d0_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add562_out;
        else 
            wvars_d0_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    wvars_d1_local_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251347_out, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add5625_out, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i2513_out, grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251_out, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            wvars_d1_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251347_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            wvars_d1_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_thr_add5625_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            wvars_d1_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i2513_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            wvars_d1_local <= grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168_add_i26_i251_out;
        else 
            wvars_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    wvars_we0_assign_proc : process(grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_we0, ap_CS_fsm_state2, wvars_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            wvars_we0 <= grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155_wvars_we0;
        else 
            wvars_we0 <= (wvars_we0_out or ap_const_logic_0);
        end if; 
    end process;


    wvars_we0_local_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            wvars_we0_local <= ap_const_logic_1;
        else 
            wvars_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    wvars_we0_out <= wvars_we0_local;

    wvars_we1_local_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            wvars_we1_local <= ap_const_logic_1;
        else 
            wvars_we1_local <= ap_const_logic_0;
        end if; 
    end process;

end behav;
