

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "38", "40", "43", "45", "59"],
		"CDFG" : "sha512Accel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bitstream", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_sha512Accel_Pipeline_VITIS_LOOP_15_2_fu_399", "Port" : "bitstream", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "38", "SubInstance" : "grp_sha512Accel_Pipeline_VITIS_LOOP_26_3_fu_442", "Port" : "bitstream", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "size", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "kValues", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "45", "SubInstance" : "grp_chunkProcessor_fu_557", "Port" : "kValues", "Inst_start_state" : "12", "Inst_end_state" : "13"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_13_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "19", "FirstState" : "ap_ST_fsm_state5", "LastState" : ["ap_ST_fsm_state15"], "QuitState" : ["ap_ST_fsm_state5"], "PreState" : ["ap_ST_fsm_state4"], "PostState" : ["ap_ST_fsm_state16"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_8_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_9_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_10_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_11_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_12_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_13_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_14_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_15_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_16_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_17_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_18_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_19_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_20_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_21_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_22_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_23_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_24_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_25_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_26_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_27_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_28_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_29_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_30_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.buffer_31_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.interHash_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.wordsout_U", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.message_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_15_2_fu_399", "Parent" : "0", "Child" : ["37"],
		"CDFG" : "sha512Accel_Pipeline_VITIS_LOOP_15_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "898", "EstimateLatencyMax" : "898",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "addSize", "Type" : "None", "Direction" : "I"},
			{"Name" : "counter", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitstream", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "bitstream_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "size", "Type" : "None", "Direction" : "I"},
			{"Name" : "addSize_1_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_15_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_15_2_fu_399.flow_control_loop_pipe_sequential_init_U", "Parent" : "36"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_26_3_fu_442", "Parent" : "0", "Child" : ["39"],
		"CDFG" : "sha512Accel_Pipeline_VITIS_LOOP_26_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "130", "EstimateLatencyMax" : "130",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "or_ln", "Type" : "None", "Direction" : "I"},
			{"Name" : "bitstream", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "bitstream_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "buffer_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "size", "Type" : "None", "Direction" : "I"},
			{"Name" : "addSize_2_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_26_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_26_3_fu_442.flow_control_loop_pipe_sequential_init_U", "Parent" : "38"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_38_4_fu_483", "Parent" : "0", "Child" : ["41", "42"],
		"CDFG" : "sha512Accel_Pipeline_VITIS_LOOP_38_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "130", "EstimateLatencyMax" : "130",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "buffer_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "size", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_38_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_38_4_fu_483.bitselect_1ns_128ns_7ns_1_1_1_U74", "Parent" : "40"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_38_4_fu_483.flow_control_loop_pipe_sequential_init_U", "Parent" : "40"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_46_5_fu_520", "Parent" : "0", "Child" : ["44"],
		"CDFG" : "sha512Accel_Pipeline_VITIS_LOOP_46_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "message", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "buffer_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_21", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_22", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_23", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_24", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_26", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_27", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_28", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_29", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "buffer_31", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_46_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_46_5_fu_520.flow_control_loop_pipe_sequential_init_U", "Parent" : "43"},
	{"ID" : "45", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557", "Parent" : "0", "Child" : ["46", "47", "48", "50", "52", "54", "57"],
		"CDFG" : "chunkProcessor",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "336", "EstimateLatencyMax" : "336",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155", "Port" : "input_r", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "57", "SubInstance" : "grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193", "Port" : "input_r", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "message", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147", "Port" : "message", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "57", "SubInstance" : "grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193", "Port" : "output_r", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "kValues", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168", "Port" : "kValues", "Inst_start_state" : "7", "Inst_end_state" : "8"}]}]},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.wValues_U", "Parent" : "45"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.wvars_U", "Parent" : "45"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147", "Parent" : "45", "Child" : ["49"],
		"CDFG" : "chunkProcessor_Pipeline_VITIS_LOOP_8_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "message", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "wValues", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_8_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_8_1_fu_147.flow_control_loop_pipe_sequential_init_U", "Parent" : "48"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155", "Parent" : "45", "Child" : ["51"],
		"CDFG" : "chunkProcessor_Pipeline_VITIS_LOOP_24_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "wvars", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_24_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_24_1_fu_155.flow_control_loop_pipe_sequential_init_U", "Parent" : "50"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163", "Parent" : "45", "Child" : ["53"],
		"CDFG" : "chunkProcessor_Pipeline_VITIS_LOOP_11_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "131", "EstimateLatencyMax" : "131",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "wValues", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_11_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_11_2_fu_163.flow_control_loop_pipe_sequential_init_U", "Parent" : "52"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168", "Parent" : "45", "Child" : ["55", "56"],
		"CDFG" : "chunkProcessor_Pipeline_VITIS_LOOP_27_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "164", "EstimateLatencyMax" : "164",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "wvars_load_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "wvars_load_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "wvars_load_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "wvars_load_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "wvars_load_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "wvars_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "wvars_load_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "wvars_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "wValues", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "thr_add562568_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "add_i26_i251347_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "thr_add56256_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "thr_add5625_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "add_i26_i25134_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "add_i26_i2513_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "thr_add562_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "add_i26_i251_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "kValues", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_27_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168.kValues_U", "Parent" : "54"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_27_2_fu_168.flow_control_loop_pipe_sequential_init_U", "Parent" : "54"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193", "Parent" : "45", "Child" : ["58"],
		"CDFG" : "chunkProcessor_Pipeline_VITIS_LOOP_34_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "wvars", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_r", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_34_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_chunkProcessor_fu_557.grp_chunkProcessor_Pipeline_VITIS_LOOP_34_4_fu_193.flow_control_loop_pipe_sequential_init_U", "Parent" : "57"},
	{"ID" : "59", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_52_7_fu_566", "Parent" : "0", "Child" : ["60"],
		"CDFG" : "sha512Accel_Pipeline_VITIS_LOOP_52_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "wordsout", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "interHash", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_52_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_sha512Accel_Pipeline_VITIS_LOOP_52_7_fu_566.flow_control_loop_pipe_sequential_init_U", "Parent" : "59"}]}
